name: Run Sanity Tests on LambdaTest

on:
  workflow_dispatch:

jobs:
  sanity-test:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Sanity Test on LambdaTest
        run: |
          echo "Triggering sanity tests on LambdaTest"

          response=$(curl --location 'https://test-manager-api.lambdatest.com/api/atm/v1/hyperexecute' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Basic c3VoZWVsOkxUXzh1b0hZMUpxbEdTUTJCUTZRVHE4ZEJuZEx4UWZTTzRsQ0o2NkY1dlJQYU1rOVZR' \
          --data '{
            "test_run_id": "01KQA28DRY3M040J418V47PNJA",
            "concurrency": 1,
            "title": "Trail Run Test"
          }')

          echo "Response: $response"
